package(
    default_visibility = [
    ],
)

licenses(["notice"])  # Apache 2.0

java_library(
    name = "golden_files_base_test",
    testonly = 1,
    srcs = ["GoldenFilesBaseTest.java"],
    deps = [
        "//third_party/java/auto:auto_value",
        "//third_party/java/junit",
    ],
)
