# Integration tests for immutable protos
load("//javatests/com/google/protobuf/contrib/immutablejs/build_def:proto_test.bzl", "proto_jsunit_test")

licenses(["notice"])  # Apache 2.0

proto_jsunit_test(
    name = "boolean_fields_test",
    srcs = [
        "boolean_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "builder_test",
    srcs = [
        "builder_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "conflicting_names_test",
    srcs = [
        "conflicting_names_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:conflicting_names_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "bytestring_fields_test",
    srcs = [
        "bytestring_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "double_fields_test",
    srcs = [
        "double_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "enum_fields_test",
    srcs = [
        "enum_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "float_fields_test",
    srcs = [
        "float_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "int_fields_test",
    srcs = [
        "int_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "uint32_fields_test",
    srcs = [
        "uint32_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "int52long_fields_test",
    srcs = [
        "int52long_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:defines",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_math_long",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "long_fields_test",
    srcs = [
        "long_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_math_long",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

genrule(
    name = "maps_all_variants_test_gen",
    outs = ["maps_all_variants_test.js"],
    cmd = "$(location //javatests/com/google/protobuf/contrib/immutablejs/integration/generator:MapsAllVariantsTestGenerator) -output $@",
    tools = ["//javatests/com/google/protobuf/contrib/immutablejs/integration/generator:MapsAllVariantsTestGenerator"],
)

proto_jsunit_test(
    name = "maps_all_variants_test",
    srcs = [
        "maps_all_variants_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:maps_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_math_long",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "maps_test",
    srcs = [
        "maps_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:maps_immutable_js_proto",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "message_fields_test",
    srcs = [
        "message_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "message_default_instance_test",
    srcs = [
        "message_default_instance_test.js",
    ],
    deps = [
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:equals_immutable_js_proto",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "message_equality_test",
    srcs = [
        "message_equality_test.js",
    ],
    deps = [
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:equals_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "oneof_test",
    srcs = [
        "oneof_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:oneofs_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "string_fields_test",
    srcs = [
        "string_fields_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//java/com/google/protobuf/contrib/immutablejs/runtime:internal_checks",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "tobuilder_test",
    srcs = [
        "tobuilder_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:accessors_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:extensions_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_math_long",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "cycle_reference_test",
    srcs = [
        "cycle_reference_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:cycle_reference_immutable_js_proto",
        "//javatests/com/google/protobuf/contrib/immutablejs/testing:proto_asserts",
        "//third_party:closure_testing_asserts",
        "//third_party:closure_testsuite",
    ],
)

proto_jsunit_test(
    name = "ambiguous_names_test",
    srcs = [
        "ambiguous_names_test.js",
    ],
    deps = [
        "//java/com/google/protobuf/contrib/immutablejs:runtime",
        "//javatests/com/google/protobuf/contrib/immutablejs/protos:ambiguous_names_immutable_js_proto",
        "//third_party:closure_testsuite",
    ],
)
