proto_jsunit_test(
    name = "bytestring_test",
    srcs = ["bytestring_test.js"],
    deps = [
    ],
)

proto_jsunit_test(
    name = "equivalence_test",
    srcs = ["equivalence_test.js"],
    deps = [
    ],
)

proto_jsunit_test(
    name = "fieldaccessor_test",
    srcs = ["fieldaccessor_test.js"],
    deps = [
    ],
)

proto_jsunit_test(
    name = "hashing_test",
    srcs = ["hashing_test.js"],
    deps = [
    ],
)

proto_jsunit_test(
    name = "listview_test",
    srcs = ["listview_test.js"],
    deps = [
    ],
)
