sh_test(
    name = "check_runfiles",
    args = [
        "java/com/google/protobuf/contrib/j2cl/options/js_enum-improto",
        "java/com/google/protobuf/contrib/j2cl/options/js_enum-j2cl.js.zip",
        "javatests/com/google/protobuf/contrib/j2cl/protos/enum_alias-improto",
        "javatests/com/google/protobuf/contrib/j2cl/protos/enum_alias-j2cl.js.zip",
    ],
    deps = ["//util/shell/gbash"],
)
