package(default_visibility = [
])

licenses(["notice"])  # Apache 2.0

generate_protos(
    name = "accessor",
    proto_file = "accessor.proto",
)

generate_protos(
    name = "ambiguous_fields",
    proto_file = "ambiguous_fields.proto",
)

generate_protos(
    name = "enum_alias",
    proto_file = "enum_alias.proto",
)

generate_protos(
    name = "extensions",
    proto_file = "extensions.proto",
)

generate_protos(
    name = "oneofs",
    proto_file = "oneofs.proto",
)

generate_protos(
    name = "empty_package",
    proto_file = "empty_package.proto",
)

generate_protos(
    name = "field_names",
    proto_file = "field_names.proto",
)

generate_protos(
    name = "native_enum",
    proto_file = "native_enum.proto",
)

generate_protos(
    name = "proto-with-dashes",
    proto_file = "proto-with-dashes.proto",
)

generate_protos(
    name = "sparse",
    proto_file = "sparse.proto",
)
