package(
    default_visibility = [
        "//visibility:public",
    ],
)

licenses(["notice"])

alias(
    name = "runtime",
    actual = "//java/com/google/protobuf/contrib/immutablejs/runtime",
)

alias(
    name = "debug",
    actual = "//java/com/google/protobuf/contrib/immutablejs/debug",
)

alias(
    name = "timestamp",
    actual = "//java/com/google/protobuf/contrib/immutablejs/util:timestamp",
)
