package(
    default_visibility = [
    ],
)

licenses(["notice"])  # Apache 2.0

java_library(
    name = "ProtoToJspb",
    srcs = ["ProtoToJspb.java"],
    deps = [
        "//third_party/java/args4j",
    ],
)
