package(
    default_visibility = [
        "//java/com/google/protobuf/contrib/immutablejs:__subpackages__",
        "//javatests/com/google/protobuf/contrib/immutablejs:__subpackages__",
    ],
)

licenses(["notice"])  # Apache 2.0

java_library(
    name = "ProtoToJspb",
    srcs = ["ProtoToJspb.java"],
    deps = [
        "//java/com/google/apps/jspb",
        "//java/com/google/protobuf",
        "//third_party/java/args4j",
    ],
)
