load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

package(
    default_visibility = [
    ],
)

licenses(["notice"])  # Apache 2.0

closure_js_library(
    name = "debug",
    srcs = ["debug.js"],
    deps = [
    ],
)
