load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

# Apache2
licenses(["notice"])

package(
    default_visibility = [
    ],
)

closure_js_library(
    name = "debug",
    srcs = ["debug.js"],
    deps = [
    ],
)
